Setup kind.
distributed-technologies/mukube-loadbalancer pull request #4
Opened 2021-03-16 11:24 UTC by jacobcrawford

2021-03-17 09:46 UTC, jaxels10 requested changes

2021-03-17 09:46 UTC, jaxels10 commented on README.md
> +The helm chart has been generated with inpsiration from the [MetalLB instalation guide](https://metallb.universe.tf/installation/).
Inspiration

2021-03-17 09:46 UTC, jaxels10 commented on README.md
> +The workflow ```test_deply``` deploys the load-balancer in a KinD cluster using a test values.yaml file in the ```test``` folder.
test_deploy?

2021-03-17 09:46 UTC, jaxels10 commented on chart/templates/metallb.yaml
> +        imagePullPolicy: {{.Values.imagePullPolicy}}
I believe the correct syntax is {{ .Values.imagePullPolicy }}. So a space missing between the curly bois and the template call on both ends.

2021-03-17 09:46 UTC, jaxels10 commented on chart/templates/metallb.yaml
> +        imagePullPolicy: {{.Values.imagePullPolicy}}
I believe the correct syntax is {{ .Values.imagePullPolicy }}. So a space missing between the curly bois and the template call on both ends.

2021-03-17 09:46 UTC, jaxels10 commented on chart/templates/metallb.yaml
> +        imagePullPolicy: {{.Values.imagePullPolicy}}
Also missing on line 305 I can see. Perhaps in the entire repo

2021-03-18 11:53 UTC, MartinSchmidt requested changes

2021-03-18 11:53 UTC, MartinSchmidt commented on .github/workflows/test_deploy.yaml
> +        uses: juliangruber/sleep-action@v1
Wouldn't bash sleep work aswell and remove an external dependency?
```suggestion
        run: sleep 30
```

2021-03-18 11:53 UTC, MartinSchmidt commented on .github/workflows/test_deploy.yaml
> +        uses: juliangruber/sleep-action@v1
Same as above.
```suggestion
        run: sleep 30
```

2021-03-18 11:58 UTC, jaxels10 approved these changes

2021-03-19 05:59 UTC, MartinSchmidt commented on .github/workflows/test_deploy.yaml
> +          time: 30s
Good point @lynderup, maybe a loop that waits for all pods and/or services to be ready?

2021-03-19 08:16 UTC, jacobcrawford commented on .github/workflows/test_deploy.yaml
> +          time: 30s
Since it is a service that gets a IP assigned, we cannot wait for this to happen. Services does not have readiness probes.
I have added a loop that checks each second if an ip has been assigned.
The negative test runs through the whole 30 seconds without finding the external IP and the other test finds the IP at some point.

2021-03-19 09:03 UTC, MartinSchmidt commented on .github/workflows/test_deploy.yaml
> +          time: 30s
@lynderup argument is that it could in theory take more than 30 seconds... Could you not do a loop `kubectl describe svc` and wait for the ip to be assigned?

2021-03-19 09:05 UTC, MartinSchmidt approved these changes

2021-03-19 09:05 UTC, merged